name: build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run tests and generate coverage report
      uses: actions-rs/tarpaulin@v0.1
      with:
        # Arguments passed to cargo-tarpaulin
        args: '--ignore-tests'

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        # Repository upload token (required)
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload (optional)
        file: ./cobertura.xml
